export const GET_PRODUCET_PROGRESS = "GET_PRODUCET_PROGRESS"
export const GET_PRODUCET_SUCCESS = "GET_PRODUCET_SUCCESS"
export const GET_PRODUCET_ERROR = "GET_PRODUCET_ERROR"

export const POST_PRODUCET_PROGRESS = "POST_PRODUCET_PROGRESS"
export const POST_PRODUCET_SUCCESS = "POST_PRODUCET_SUCCESS"
export const POST_PRODUCET_ERROR = "POST_PRODUCET_ERROR"

export const DELETE_PRODUCET_PROGRESS = "DELETE_PRODUCET_PROGRESS"
export const DELETE_PRODUCET_SUCCESS = "DELETE_PRODUCET_SUCCESS"
export const DELETE_PRODUCET_ERROR = "DELETE_PRODUCET_ERROR"

export const UPDATE_PRODUCET_PROGRESS = "UPDATE_PRODUCET_PROGRESS"
export const UPDATE_PRODUCET_SUCCESS = "UPDATE_PRODUCET_SUCCESS"
export const UPDATE_PRODUCET_ERROR = "UPDATE_PRODUCET_ERROR"